app/urls.py
from flask import Blueprint

admin = Blueprint('admin', __name__, url_prefix='/admin')
auth = Blueprint('auth', __name__, url_prefix='/auth')
article = Blueprint('article', __name__, url_prefix='/articles')
comment = Blueprint('comment', __name__, url_prefix='/article/comment')
user = Blueprint('user', __name__, url_prefix='/user')
home = Blueprint('home',__name__, url_prefix='/')


from app.home import views
from app.auth import views
from app.profile import views
from app.article import views
from app.comment import views

app/comment/views.py
from flask import redirect, url_for, flash
from app.comment.forms import CommentForm
from app.models import Comment
from app.urls import comment
from flask_login import current_user, login_required


# New Comment View
@login_required
@comment.route('new/<int:article_id>', methods=['POST'])
def new_comment(article_id):
    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        comment = Comment(body=comment_form.body.data,
                          user_id=current_user.id, article_id=article_id)
        comment.save()
        flash("Comment created successfully!")
    else:
        flash("Please fill the form with the correct details and try again")
    return redirect(url_for('article.detail', article_id=article_id))


# Update Comment View
@comment.route('/update/<int:article_id>/<int:comment_id>', methods=['POST'])
def update(article_id, comment_id):
    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        comment = Comment.query.filter(id=comment_id).first()
        comment.update()
        flash("Comment updated successfully")
    flash("Please fill the form with the correct details and try again")
    return redirect(url_for('article.detail', article_id=article_id))


# Delete Comment View
@login_required
@comment.route('/<int:article_id>/delete/<int:comment_id>', methods=['POST'])
def delete(comment_id, article_id):
    comment = Comment.query.get(comment_id)
    comment.delete()
    flash("Comment deleted successfully!")
    return redirect(url_for('article.detail', article_id=article_id))

app/templates/forms/new_article.html
{% extends "base.html" %}
{% block content %}
  <div class="article-container">
    <div class="container mb-5">
      <h3 class="text-center custom-color-2">Article Form</h3>
      <div class="row">
        <div class="col-auto col-lg-10 bg-light p-5 mx-auto form-text">
          <form method="POST" enctype=multipart/form-data >
            {{article_form.csrf_token}}
            {% if edit_article %}
              <div class="form-group">
                <input type="file" name="photo" id="photo" >
              </div>
              <div class="form-group">
                {{article_form.title(class="article-title", placeholder="Title...", value=article.title)}}
              </div>
              <div class="form-group">
                {{article_form.category(class='article-category', placeholder="Post category", value=article.category)}}
              </div>
              <div class="form-group">
                <textarea name="body" class="article-body" onkeyup="adjustArticleBody(this)" onfocus="adjustArticleBody(this)">{{article.body}}</textarea>
              </div>
              <button type="submit" class="btn btn-outline-info custom-color-2">Update Article</button>
            {% else %}
              <div class="form-group">
                <input type="file" name="photo" id="photo" >
              </div>
              <div class="form-group">
                {{article_form.title(class="article-title", placeholder="Title...")}}
              </div>
              <div class="form-group">
                {{article_form.category(class='article-category', placeholder="Post category")}}
              </div>
              <div class="form-group">
                {{ article_form.body(class="article-body", placeholder="Post content", onkeyup="adjustArticleBody(this)") }}
              </div>
              {{article_form.submit(class='btn btn-outline-info custom-color-2')}}
          {% endif %}
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/forms/new_comment.html
  <div class="form">
    <form action="{{url_for('comment.new_comment', article_id=article.id)}}" method="POST">
      {{comment_form.csrf_token}}
      <div class="form-group">
      {{ comment_form.body(class="article-body px-3 pt-3 text-muted bg-light", placeholder="Share your thoughts...", onkeyup="adjustArticleBody(this)" )}}
    </div>
      {{comment_form.submit(class='submit-btn btn btn-sm btn-outline-success mt-0')}}
    </form>
  </div>

app/templates/forms/subscribe.html
<div class="subscription-container">
  <div class="subscription-overlay"></div>
  <div class="subscription-form-container">
    <div class="container">
      <div class="row">
        <div class="col col-lg-6 mx-auto">
          <div class="subscription-form">
            <i class="fas fa-times close-subscription"></i>
            <h4 class="text-center text-white pt-5">Notification Subscription</h4>
            <form class="p-5" id="subscription-form" action="{{url_for('auth.subscription')}}" method="POST">
            <input type="email" class="form-control" name="email" placeholder="Enter email address" required value="">
          <button type="submit" class="btn btn-outline-info mt-4 px-5">Submit</button>
        </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>