app/urls.py
from flask import Blueprint

admin = Blueprint('admin', __name__, url_prefix='/admin')
auth = Blueprint('auth', __name__, url_prefix='/auth')
article = Blueprint('article', __name__, url_prefix='/articles')
comment = Blueprint('comment', __name__, url_prefix='/article/comment')
user = Blueprint('user', __name__, url_prefix='/user')
home = Blueprint('home',__name__, url_prefix='/')


from app.home import views
from app.auth import views
from app.profile import views
from app.article import views
from app.comment import views

app/models.py
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from app import db
from flask_login import UserMixin
from app import login_manager


class Subscriber(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), nullable=False, unique=True)
    joined_date = db.Column(db.DateTime, default=datetime.now())
    unsubscribed_date = db.Column(db.DateTime, nullable=True)
    author_id = db.Column(
        db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), default=1)

    def subscribe(self):
        db.session.add(self)
        db.session.commit()

    def unsubscribe(self):
        db.session.delete(self)
        db.session.commit()


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), nullable=False, unique=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    hashed_password = db.Column(db.String(255), nullable=False)
    joined_at = db.Column(db.DateTime, default=datetime.now())
    updated_at = db.Column(db.DateTime, onupdate=datetime.now())
    profile_pic_path = db.Column(db.String, nullable=True, unique=True)
    comments = db.relationship(
        "Comment", backref="user", lazy=True, cascade="all, delete")
    is_admin = db.Column(db.Boolean, default=False)
    subscribers = db.relationship(
        'Subscriber', backref='author', lazy=True, cascade="all, delete")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.hashed_password = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.hashed_password, password)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def update(self):
        db.session.commit()


class Admin(User):
    articles = db.relationship('Article', backref='author', lazy=True)

    def __repr__(self):
        return self.username


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    author_id = db.Column(
        db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    title = db.Column(db.String(255), nullable=False)
    body = db.Column(db.Text(), nullable=False)
    category = db.Column(db.String, default='General')
    image_path = db.Column(db.String(50), nullable=True)
    comments = db.relationship(
        'Comment', backref='article', lazy=True, cascade='all, delete')
    created_at = db.Column(db.DateTime, default=datetime.now())
    updated_at = db.Column(db.DateTime, onupdate=datetime.now())

    def save(self):
        db.session.add(self)
        db.session.commit()

    def update(self):
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return self.body


class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    article_id = db.Column(db.Integer, db.ForeignKey(
        'article.id', ondelete='CASCADE'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey(
        'user.id', ondelete='CASCADE'), nullable=False)
    body = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.now())
    updated_at = db.Column(db.DateTime, onupdate=datetime.now())

    def save(self):
        db.session.add(self)
        db.session.commit()

    def update(self):
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return self.body

app/article/views.py
from flask import request, flash, render_template, redirect, url_for
from app.urls import article
from flask_login import login_required, current_user
from .forms import ArticleForm
from app.comment.forms import CommentForm
from app.models import Article, Subscriber
from sqlalchemy import desc, func
from datetime import date
from app import photos
from app.email.email import mail_message
from time import sleep


# All Articles
@article.route('/published/<string:category>')
@article.route('/<string:category>')
def articles(category):
    category = category.lower()
    if category == 'today':
        articles = Article.query.filter(
            func.date(Article.created_at) == date.today()).order_by(desc('created_at')).all()
    elif category == "this_week":
        articles = Article.query.order_by(desc(Article.created_at)).all()
    else:
        articles = Article.query.order_by(desc('created_at')).all()
    if request.path:
        return render_template('user_articles.html', articles=articles, category=category)
    return render_template('index.html', articles=articles)


# Add New Article
@article.route('/new', methods=['GET', 'POST'])
@login_required
def create_article():
    article_form = ArticleForm()
    if article_form.validate_on_submit():
        title = article_form.title.data
        body = article_form.body.data
        category = article_form.category.data.lower()
        article = Article(author_id=current_user.id,
                          title=title, body=body, category=category)
        if "photo" in request.files:
            filename = request.files["photo"]
            if filename:
                article.image_path = f"photos/{photos.save(filename)}"
        article.save()
        subscribers = Subscriber.query.all()
        if subscribers:
            for subscriber in subscribers:
                mail_message("Welcome to Flask Blog IO!",
                             "email/welcome_user", subscriber.email)
            sleep(0.05)
        flash("Article created successfully!")
        flash(f"Emailed {len(subscribers)} subscribers")
        return redirect(request.args.get('next') or url_for('article.articles', category=category))
    return render_template('forms/new_article.html', article_form=article_form)


# Display Article Details
@article.route('/detail/<int:article_id>/')
def detail(article_id):
    comment_form = CommentForm()
    article = Article.query.filter_by(id=article_id).first()
    return render_template('article_detail.html', article=article, comment_form=comment_form)


# Update Article Details
@article.route('/update/<int:article_id>/', methods=['GET', 'POST'])
@login_required
def update(article_id):
    article = Article.query.filter_by(id=article_id).first()
    article_form = ArticleForm()
    if request.method == 'POST':
        article.title = article_form.title.data
        article.category = article_form.category.data
        article.body = article_form.body.data
        if "photo" in request.files:
            filename = request.files["photo"]
            if filename:
                article.image_path = f"photos/{photos.save(filename)}"
        article.update()
        return redirect(url_for('article.detail', article_id=article_id))
    return render_template('forms/new_article.html', article=article, edit_article=True, article_form=article_form)


# Delete Article
@article.route('/delete/<int:article_id>', methods=['POST'])
@login_required
def delete(article_id):
    article = Article.query.get(article_id)
    if article is not None:
        article.delete()
        flash(f"{article.title} deleted successfully")
        return redirect(url_for("article.articles", category='all'))
    flash("No such article")

app/profile/views.py
from flask import render_template, redirect, url_for, request
from flask_login import login_required
from app.urls import user
from app.models import User, Article
from app import photos
from sqlalchemy import desc
import os


@user.route('/profile/<int:user_id>', methods=['GET', 'POST'])
@login_required
def profile(user_id):
    articles = Article.query.order_by(
        desc('created_at')).filter_by(author_id=user_id).all()
    return render_template('profile.html', articles=articles)


@user.route('/profile/<int:user_id>/update', methods=['POST'])
def update(user_id):
    user = User.query.filter_by(id=user_id).first()
    if 'photo' in request.files:
        if user.profile_pic_path:
            user_image = f"/{user.profile_pic_path.split('/')[1]}"
            path = os.path.abspath(os.environ.get(
                'UPLOADED_PHOTOS_DEST') + user_image)
            if os.path.exists(path):
                os.remove(path)

        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        user.save()
    return redirect(url_for('user.profile', user_id=user_id))

app/templates/article_detail.html
{% extends "base.html" %}
{% import 'macro.html' as macro %}
{% block content %}
<section class="form pb-5">
  <div class="container-fluid px-5 pb-5">
    <div class="row pb-5">
      {{macro.display_article_detail(article, current_user, comment_form)}}
    </div>
  </div>
</section>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>

  <link rel="stylesheet" href="{{url_for( 'static', filename='css/bootstrap.min.css')}}">
  
  <link rel="stylesheet" href="{{url_for( 'static', filename='css/style.css')}}">

  <title>Blog</title>
</head>
<body>
  {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissible text-center fade show m-0" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
    {% endif %}
  {% endwith %}

  {% block navbar %}
      {% include 'navbar.html' %}
  {% endblock %}
  
  {% block account %}
  {% include 'accounts/account.html' %}
  {% endblock %}

  {% block subscription_form %}
    {% include 'forms/subscribe.html' %}
  {% endblock %}
  
  {% block content %}
          
  {% endblock %}

  {% block footer %}
    {% include 'copyright.html' %}
  {% endblock %}


 
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{{url_for('static', filename='js/jquery-3.6.0.js')}}"></script>
    <script src="{{url_for('static', filename='js/popper-2.11.2.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/script.js')}}"></script>
</body>
</html>

app/templates/copyright.html
<div class="copyright mt-5">
  <div class="container-fluid custom-bg">
    <div class="row">
      <div class="col mx-auto text-center">
        <footer>
          <a class="nav-link custom-color" href="http://github.com/brianmwevi" target="_blank">Designed By &copy; Brian Mwevi</a>
        </footer>
      </div>
    </div>
  </div>
</div>

app/templates/index.html
{% extends 'base.html' %}
{% import 'macro.html' as macro %}

{% block content %}
<!-- Homepage Start -->
<section class="home">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-4 mx-auto home-text">
          <h3 class="mb-3">The Importance Of Writing Is Breaking Down Complex Ideas Into Chunks Of Comprehensible Knowledge</h3>
          {% if quote %}
            <div class="row">
              <div class="col-lg-1 m-0 p-0">
                <i class="fas fa-quote-left fa-2x custom-color"></i>
              </div>
              <div class="col-lg-10 m-0 p-0 text-center custom-color">                  
              {{quote.quote}}              
              </div>
              <div class="col-lg-1 p-0 m-0 text-right">
                <i class="fas fa-quote-right fa-2x custom-color"></i>
              </div>
            </div>
          {% endif %}
          <p class="text-center text-white mt-5"><i class="fas fa-angle-double-down fa-3x"></i></p>
      </div>
    </div>
  </div>
  </section>
  <!-- Homepage End -->

  <!-- Home Articles Start -->
  <div id="articles" class="pt-5">
    {% block articles %}
    {% include "user_articles.html" %}
  {% endblock %}
  </div>
  <!-- Home Articles End -->
{% endblock %}

app/templates/macro.html
<!-- Display All Articles -->
{% macro display_all_articles(articles,user) %}
  {% for article in articles %}
  <div class="col-lg-3 article-image my-auto">
    <a class="p-0 m-0" href="{{url_for('article.detail', article_id=article.id)}}">
      <img src="/static/{{article.image_path}}" class="img-fluid rounded p-0 m-0" alt="Article Image">
    </a>
  </div>
  <div class="col-lg-9 my-2 bg-light">
    <div class="article-text">
      <h3>
        <a class="nav-link text-secondary" href="{{url_for('article.detail',article_id=article.id)}}">{{article.title}}</a>
      </h3>
      <p>
        <a class="nav-link p-0 m-0 text-secondary" href="{{url_for('article.detail',article_id=article.id)}}">{{article.body | truncate(400)}}</a>
      </p>
      <p>
        <i class="fas fa-user-edit custom-color-2"></i>
        <a href="#" class="text-muted custom-color-2"><small>{{article.author}}</small></a>
        <i class="fas fa-comment-alt ml-4 custom-color-2"></i>
        <sup class="ml-1">{{article.comments | length}}</sup>
      </p>
      <p class="text-muted custom-color-2"><small><i class="fas fa-clock pt-1 p-1"></i>{{article.created_at.strftime('%d %B %Y at %I %p')}}</small></p>
    </div>
  </div>
  {% endfor %}
{%endmacro%}

<!-- Delete Article Macro -->
{% macro display_article_detail(article,user, comment_form) %}
<div class="col-lg-2 px-0">
  <p class="mt-5">
    <strong>Published on: </strong>{{article.created_at.strftime('%d %B %Y')}}
  </p>
  <p>
    <strong>Comments: </strong>{{article.comments|length}}
  </p>
  <!-- Crude Operations Start -->
    {% if user.is_authenticated and article.author_id == user.id %}
    <a href="{{url_for('article.update', article_id=article.id)}}" class="btn btn-sm btn-primary mr-2">Edit Article</a>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-sm btn-danger ml-2" data-toggle="modal" data-target="#deleteModal">
      Delete Article
    </button>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title custom-color-2" id="deleteModalLabel">Are you sure you want to delete?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body custom-color-2">
          {{article.title|truncate(50)}}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn custom-bg text-white" data-dismiss="modal">Cancel</button>
            <form action="{{url_for('article.delete', article_id=article.id)}}" method="POST">
              <button class="btn bg-danger text-white">Confirm</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
    <!-- Crude Operations End -->
</div>
  <div class="col-lg-8 px-5 bg-light">
    <div class="article-title">
      <h2 class="text-center custom-color-2">{{article.title}}</h2>
    </div>
    <div class="article-img-container">
      <img class="article-detail-img" src="/static/{{article.image_path}}" alt="{{article.category}}">
    </div>
    <div class="article-body custom-color-2">
      <p>{{article.body}}</p>
    </div>
    {% if user.is_authenticated and user.id != article.author_id %}
      <button class="btn btn-outline-info btn-sm toggle-comment-form">Comment</button>
      <div class="comment-form mt-2">
        {% include "forms/new_comment.html" %}
      </div>
    {% endif %}
    {% if article.comments %}
      <div class="mt-3 w-75">
        <p class="p-0 m-0">Comments</p>
        {% for comment in article.comments %}
          <div class="text-muted custom-color-2">
            {% if user.is_authenticated and article.author_id == user.id %}
            <form class="delete-comment-form float-right" id="deleteCommentForm{{comment.id}}" action="{{url_for('comment.delete', comment_id=comment.id, article_id=article.id )}}" method="POST">
              <button type="submit" class="btn p-0"><i class="fas fa-trash custom-color-2"></i></button>
            </form>
          {% endif %}
            <p class="comment-box" id="comment{{comment.id}} ">
              <strong class="badge badge-dark mr-1">@{{comment.user.username}}</strong>
            <small>{{comment.body}}</small><br>
            <small><i class="fas fa-time"></i>{{comment.created_at.strftime('%d %b at %I %p')}}</small>
            </p>
          </div>
        {% endfor %}
      </div>
    {% endif %}
  </div>
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark float-left w-100 sticky-top custom-color custom-bg py-1">
  <div class="container-fluid px-5">
    <a href="/" class="navbar-brand text-white pt-0">
      <strong class="my-auto">Blog App</strong>
    </a>
    <button class="navbar-toggler" data-target="#main-nav" data-toggle="collapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="main-nav">
    <ul class="navbar-nav ml-auto my-auto">
    {% if current_user.is_authenticated and current_user.is_admin %}
      <li class="nav-item mt-3">
        <a href="{{url_for('article.create_article')}}" class="nav-link text-white">New Article</a>
      </li>
      <li class="nav-item mt-3">
        <a href="{{url_for('article.articles', category='all')}}" class="nav-link  text-white">Articles</a>
      </li>
      <li class="nav-item mt-3">
        <a href="{{url_for('auth.logout')}}" class="nav-link text-white">Logout</a>
      </li>
      {% if current_user.profile_pic_path %}
        <li class="nav-item mt-3 my-auto">
          <a href="{{url_for('user.profile', user_id=current_user.id)}}" class="nav-link text-white">
            <img src="{{url_for('static', filename=current_user.profile_pic_path)}}" alt="Profile Picture" class="profile-pic">
          </a>
        </li>
      {% else %}
        <li class="nav-item mt-3">
          <a href="{{url_for('user.profile', user_id=current_user.id)}}" class="nav-link text-white">Profile</a>
        </li>
      {% endif %}
      {% elif current_user.is_authenticated %}
          <li class="nav-item py-3">
          <button class="subscription-btn btn btn-outline-light custom-color mx-2">Subscribe
          </button>
        </li> 
         <li class="nav-item py-3 mx-2">
        <a href="{{url_for('article.articles', category='all')}}" class="px-3 py-2 btn btn-sm btn-outline-light custom-color">Articles</a>
      </li>
        <li class="nav-item py-3"><a href="{{url_for('auth.logout')}}" class="btn btn-light mx-2">Logout</a></li>
        {% else %}
        <li class="nav-item py-3">
          <button class="subscription-btn btn btn-outline-light custom-color mx-2">Subscribe
          </button>
        </li>  
        <li class="nav-item py-3">
          <a href="#articles" class="btn btn-outline-light custom-color mx-2">Articles
          </a>
        </li>      
        <li class="nav-item py-3">
          <button class="btn account-signup btn-outline-light custom-color mx-2 my-sm-0">
          Login/Register</button>
        </li>
      {% endif %}
      </ul>
    </div>
  </div>
</nav>

app/templates/profile.html
{% extends "base.html" %}
{% import 'macro.html' as macro %}
{% block content %}
<section class="profile form">
  <div class="container-fluid px-5">
    <div class="row">
      <div class="col-lg-8 mt-5 p-5">
        <h3 class="pb-3 custom-color-2">My Published Articles</h3>
        <div class="row">
          {{macro.display_all_articles(articles, current_user)}}
        </div>
      </div>
      <div class="col-lg-4 mx-aut mt-5 p-5">
          <h3>Profile Details</h3>
        <p><strong>Email Address: </strong><span class="badge custom-bg text-white">{{current_user.email}}</span></p>
        <p><strong>Username: </strong><span class="badge custom-bg text-white">{{current_user.username}}</span></p>
        <p><strong>Published Articles: </strong><span class="badge custom-bg text-white">{{articles|length}}</span></p>
        <p><strong>Comments: </strong><span class="badge custom-bg text-white">{{current_user.comments|length}}</span></p>
        <p><strong>Joined: </strong><span class="badge custom-bg text-white">{{current_user.joined_at.strftime('%d %b %Y')}}</span></p>
        <p><strong>Subscribers: </strong><span class="badge custom-bg text-white">{{current_user.subscribers|length}}
        </span></p>
        <form action="{{url_for('user.update', user_id=current_user.id)}}" method="POST" enctype="multipart/form-data")">
          <p><strong>Update profile picture</strong></p>
          <input type="file" name="photo" class="form-control" required>
          <button class="btn btn-outline-info btn-sm mt-3">Submit</button>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/user_articles.html
{% if category %}
{% extends 'base.html' %}
{% endif %}
{% import "macro.html"  as macro %}

{% block navbar %}
  {% if category %}
    {% include 'navbar.html' %}
  {% endif %}
{% endblock %}
{% block content %}
<section>
  <div class="container-fluid px-5">
    <div class="row px-5">
      <!-- Right articles Content Start -->
      <div class="col-lg-9">
        <div class="row">
          <div class="col">
            <div class="navbar">
              <ul class="nav nav-tabs p-0 m-0">
                <li class="nav-item">
                  <a href="{{url_for('article.articles', category='today')}}" class="nav-link text-secondary">
                    <i class="fab fa-gripfire text-danger"></i>
                    Today
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{{url_for('article.articles', category='this_week')}}" class="nav-link text-secondary">
                    <i class="fas fa-bolt"></i>
                    This week
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{{url_for('article.articles', category='all')}}" class="nav-link text-secondary">
                    <i class="far fa-clock"></i>
                    All
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row">
          {{macro.display_all_articles(articles, current_user)}}
        </div>
      </div>
      <!-- Right articles Content End -->
      <div class="col-lg-3 mt-5 text-center"> 
          <p><i class="fas fa-tags custom-color-2"></i>Tags</p>
          {% for article in articles %}
            <div class="badge custom-bg text-white px-2 py-1 m-2">{{article.category}}</div>
          {% endfor %}
        </div>
    </div>
  </div>
</section> 
{% endblock %}